version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: qmdverify
    main: .
    binary: qmdverify
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv7
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: rmitchellscott
    name: rm-qmd-verify-cli
  draft: false
  prerelease: auto
  mode: replace
  name_template: "v{{.Version}}"

homebrew_casks:
  - name: qmdverify
    skip_upload: "{{ .IsSnapshot }}"
    binaries:
      - qmdverify
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qmdverify"]
          end
    homepage: https://github.com/rmitchellscott/rm-qmd-verify-cli
    description: QMD file compatibility checker for reMarkable devices
    license: MIT
    repository:
      owner: rmitchellscott
      name: homebrew-tap
      git:
        url: 'ssh://git@github.com/rmitchellscott/homebrew-tap.git'
        private_key: '{{ envOrDefault "HOMEBREW_PRIVATE_KEY" "" }}'

announce:
  skip: true
